export enum Plan {
  FREE = "FREE",
  PRO = "PRO",
}

export enum GenerationType {
  TEXT_TO_IMAGE = "TEXT_TO_IMAGE",
  AI_CHATBOT = "AI_CHATBOT",
  CODE_CHECKER = "CODE_CHECKER",
  IMAGE_BACKGROUND_REMOVER = "IMAGE_BACKGROUND_REMOVER",
  IMAGE_CAPTION_GENERATOR = "IMAGE_CAPTION_GENERATOR",
  RESUME_ANALYZER = "RESUME_ANALYZER",
  LANGUAGE_TRANSLATOR = "LANGUAGE_TRANSLATOR",
  GRAMMER_IMPROVER = "GRAMMER_IMPROVER",
  TEXT_TO_SPEECH = "TEXT_TO_SPEECH",
  SPEECH_TO_TEXT = "SPEECH_TO_TEXT",
  IMAGE_TO_VIDEO = "IMAGE_TO_VIDEO",
  TEXT_TO_VIDEO = "TEXT_TO_VIDEO",
}

export enum GenerationStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum PaymentGateway {
  STRIPE = "STRIPE",
  SSLCOMMERZ = "SSLCOMMERZ",
  PAYPAL = "PAYPAL",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}
