export const envVars = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL as string,
  API_BASE_URL_FOR_HOME: process.env
    .NEXT_PUBLIC_API_BASE_URL_FOR_HOME as string,

  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET as string,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET as string,

  PUBLIC_CLOUDINARY_CLOUD_NAME: process.env
    .NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME as string,
  CLOUDINARY_UPLOAD_PRESET: process.env
    .NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET as string,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME as string,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY as string,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET as string,
};
